[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.backends.legacy:build"

[project]
name = "rhapsodist"
version = "0.3.0"
requires-python = ">=3.10"
dependencies = ["snakemake>=8.12"]

[project.scripts]
rhapsodist = "rhapsodist.cli:main"

[tool.setuptools.packages.find]
include = ["rhapsodist*"]
